import type { Metadata } from "next";
import StoreProvider from "./StoreProvider";
import ThemeSwitchProvider from "./components/ThemeSwitchProviders";
import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark:bg-custom-gradient-dark dark:text-white">
        <div className="bg-fade dark:bg-custom-fade-dark  min-h-screen ">
          <StoreProvider>
            <ThemeSwitchProvider>
              <Navbar />
              {children}
            </ThemeSwitchProvider>
          </StoreProvider>
        </div>
      </body>
    </html>
  );
}
